// ============================================================
// BOV (Broker Opinion of Value) PDF Generator
// Professional 8-12 page branded PDF report for NYC buildings.
// Follows jsPDF patterns from invoice-simple-pdf.ts / deal-pdf.ts.
// ============================================================

import jsPDF from "jspdf";
import type { BovPayload, BovCompData, BovExpenseLineItem } from "./bov-types";

// ── Colors ───────────────────────────────────────────────────

type RGB = [number, number, number];

const WHITE: RGB = [255, 255, 255];
const BLACK: RGB = [33, 33, 33];
const DARK: RGB = [15, 23, 42];
const GRAY: RGB = [100, 116, 139];
const LIGHT_GRAY: RGB = [226, 232, 240];
const BG_LIGHT: RGB = [248, 250, 252];
const GREEN: RGB = [22, 163, 74];
const RED: RGB = [220, 38, 38];
const AMBER: RGB = [217, 119, 6];

// ── Formatters ───────────────────────────────────────────────

function fmt(n: number): string {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(n);
}

function fmtFull(n: number): string {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2 }).format(n);
}

function fmtK(n: number): string {
  if (n >= 1e6) return `$${(n / 1e6).toFixed(2)}M`;
  if (n >= 1000) return `$${Math.round(n / 1000).toLocaleString()}K`;
  return fmt(n);
}

function fmtNum(n: number): string {
  return new Intl.NumberFormat("en-US").format(n);
}

function fmtPct(n: number): string {
  return `${n.toFixed(1)}%`;
}

function fmtDate(iso: string): string {
  try {
    return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(iso));
  } catch { return iso || "N/A"; }
}

function hexToRgb(hex: string): RGB {
  const h = hex.replace("#", "");
  return [parseInt(h.slice(0, 2), 16) || 30, parseInt(h.slice(2, 4), 16) || 64, parseInt(h.slice(4, 6), 16) || 175];
}

function truncate(s: string, max: number): string {
  return s.length > max ? s.slice(0, max - 1) + "\u2026" : s;
}

function sanitizeFilename(str: string): string {
  return str.replace(/[^a-zA-Z0-9\s-]/g, "").trim().replace(/\s+/g, "-").substring(0, 60);
}

// ── Main Generator ───────────────────────────────────────────

export function generateBovPdf(payload: BovPayload): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const W = 612;
  const H = 792;
  const ML = 50;
  const MR = 50;
  const CW = W - ML - MR; // 512

  const PRIMARY: RGB = hexToRgb(payload.branding.primaryColor);
  const ACCENT: RGB = hexToRgb(payload.branding.accentColor);

  // Lighter tints for backgrounds
  const PRIMARY_LIGHT: RGB = [
    Math.min(255, PRIMARY[0] + Math.round((255 - PRIMARY[0]) * 0.88)),
    Math.min(255, PRIMARY[1] + Math.round((255 - PRIMARY[1]) * 0.88)),
    Math.min(255, PRIMARY[2] + Math.round((255 - PRIMARY[2]) * 0.88)),
  ];

  let y = 0;
  let page = 1;

  // ── Utility: check page break ─────────────────────────────
  function checkBreak(needed: number): void {
    if (y + needed > H - 60) {
      addFooter();
      doc.addPage();
      page++;
      y = 50;
    }
  }

  // ── Utility: footer ───────────────────────────────────────
  function addFooter(): void {
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.setFont("helvetica", "normal");
    doc.text(payload.branding.companyName, ML, H - 20);
    doc.text(`Page ${page}`, W / 2, H - 20, { align: "center" });
    doc.text("Generated by VettdRE", W - MR, H - 20, { align: "right" });
  }

  // ── Utility: section title ────────────────────────────────
  function sectionTitle(text: string): void {
    checkBreak(30);
    doc.setFontSize(13);
    doc.setTextColor(...PRIMARY);
    doc.setFont("helvetica", "bold");
    doc.text(text, ML, y);
    doc.setDrawColor(...LIGHT_GRAY);
    doc.setLineWidth(0.5);
    doc.line(ML, y + 4, W - MR, y + 4);
    y += 22;
  }

  // ── Utility: label-value pair ─────────────────────────────
  function labelValue(label: string, value: string, indent = 0): void {
    checkBreak(14);
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GRAY);
    doc.text(label, ML + indent, y);
    doc.setTextColor(...DARK);
    doc.setFont("helvetica", "bold");
    doc.text(value, ML + 180 + indent, y);
    y += 14;
  }

  // ── Utility: body text (wrapped) ──────────────────────────
  function bodyText(text: string, maxWidth?: number): void {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...DARK);
    const lines = doc.splitTextToSize(text, maxWidth || CW);
    for (const line of lines) {
      checkBreak(13);
      doc.text(line, ML, y);
      y += 13;
    }
  }

  // ── Utility: small muted text ─────────────────────────────
  function mutedText(text: string): void {
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(...GRAY);
    const lines = doc.splitTextToSize(text, CW);
    for (const line of lines) {
      checkBreak(12);
      doc.text(line, ML, y);
      y += 12;
    }
  }

  // ─────────────────────────────────────────────────────────
  // PAGE 1 — Cover Page
  // ─────────────────────────────────────────────────────────

  // Full-width brand color header bar
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, W, 100, "F");

  // Company name / logo
  doc.setTextColor(...WHITE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(payload.branding.companyName.toUpperCase(), ML, 55);

  if (payload.branding.website) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(payload.branding.website, ML, 72);
  }

  // Property address — centered large
  y = 220;
  doc.setTextColor(...DARK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  const addrLines = doc.splitTextToSize(payload.property.address, CW);
  for (const line of addrLines) {
    doc.text(line, W / 2, y, { align: "center" });
    y += 36;
  }

  // Borough / Neighborhood / Zip
  y += 8;
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GRAY);
  const locParts = [payload.property.borough, payload.property.neighborhood, payload.property.zip].filter(Boolean);
  doc.text(locParts.join("  \u2022  "), W / 2, y, { align: "center" });

  // Document title
  y += 60;
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY);
  doc.text("Broker Opinion of Value", W / 2, y, { align: "center" });

  // Date
  y += 30;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GRAY);
  doc.text(`Prepared ${fmtDate(payload.generatedAt)}`, W / 2, y, { align: "center" });

  // Broker info block
  y += 50;
  doc.setFontSize(10);
  doc.setTextColor(...DARK);
  doc.setFont("helvetica", "bold");
  doc.text("Prepared by:", W / 2, y, { align: "center" });
  y += 18;
  doc.setFontSize(12);
  doc.text(payload.generatedBy.name, W / 2, y, { align: "center" });
  if (payload.generatedBy.title) {
    y += 16;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(payload.generatedBy.title, W / 2, y, { align: "center" });
  }
  y += 16;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(payload.generatedBy.email, W / 2, y, { align: "center" });
  if (payload.generatedBy.phone) {
    y += 14;
    doc.text(payload.generatedBy.phone, W / 2, y, { align: "center" });
  }
  if (payload.generatedBy.licenseNumber) {
    y += 14;
    doc.text(`License #${payload.generatedBy.licenseNumber}`, W / 2, y, { align: "center" });
  }

  // Bottom accent bar
  doc.setFillColor(...ACCENT);
  doc.rect(0, H - 30, W, 30, "F");
  doc.setFontSize(8);
  doc.setTextColor(...WHITE);
  doc.setFont("helvetica", "normal");
  doc.text(payload.branding.companyName, W / 2, H - 12, { align: "center" });

  // ─────────────────────────────────────────────────────────
  // PAGE 2 — Executive Summary
  // ─────────────────────────────────────────────────────────

  doc.addPage();
  page++;
  y = 50;

  sectionTitle("Executive Summary");

  // Key stats callout box
  const boxX = W - MR - 170;
  const boxW = 170;
  let boxY = y;
  doc.setFillColor(...PRIMARY_LIGHT);
  doc.roundedRect(boxX, boxY, boxW, 200, 4, 4, "F");

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY);
  doc.text("Key Metrics", boxX + 10, boxY + 18);
  let by = boxY + 34;

  const keyStats: [string, string][] = [
    ["Building Class", payload.property.buildingClass],
    ["Units", `${payload.property.unitsTotal}`],
    ["Gross SF", fmtNum(payload.property.grossSqft)],
    ["Year Built", `${payload.property.yearBuilt}`],
    ["Stories", `${payload.property.stories}`],
    ["Zoning", payload.property.zoning],
    ["Assessed Value", fmtK(payload.property.assessedTotalValue)],
  ];

  if (payload.valuation) {
    keyStats.push(["Est. Value", `${fmtK(payload.valuation.reconciledLow)} - ${fmtK(payload.valuation.reconciledHigh)}`]);
  }
  if (payload.capRate) {
    keyStats.push(["Market Cap Rate", fmtPct(payload.capRate.marketCapRate)]);
  }

  for (const [label, val] of keyStats) {
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GRAY);
    doc.text(label, boxX + 10, by);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text(val, boxX + boxW - 10, by, { align: "right" });
    by += 16;
  }

  // Resize box to fit
  const actualBoxH = by - boxY + 8;
  // Redraw box with correct height
  doc.setFillColor(...PRIMARY_LIGHT);
  doc.roundedRect(boxX, boxY, boxW, actualBoxH, 4, 4, "F");
  // Re-render key stats
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY);
  doc.text("Key Metrics", boxX + 10, boxY + 18);
  by = boxY + 34;
  for (const [label, val] of keyStats) {
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GRAY);
    doc.text(label, boxX + 10, by);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text(val, boxX + boxW - 10, by, { align: "right" });
    by += 16;
  }

  // Narrative (left side, wrapping around callout box)
  const narrativeWidth = CW - boxW - 20;
  const prop = payload.property;

  let narrative = `${prop.address} is a ${prop.stories}-story, ${prop.buildingClassDescription || `Class ${prop.buildingClass}`} building `;
  narrative += `located in ${prop.borough}${prop.neighborhood ? ` (${prop.neighborhood})` : ""}. `;
  narrative += `Built in ${prop.yearBuilt}, the property contains ${prop.unitsTotal} units `;
  narrative += `across ${fmtNum(prop.grossSqft)} gross square feet on a ${fmtNum(prop.lotSqft)} SF lot.`;

  bodyText(narrative, narrativeWidth);
  y += 6;

  if (payload.ownership) {
    const ow = payload.ownership;
    let owText = `The property is owned by ${ow.registeredOwner}`;
    if (ow.managingAgent) owText += `, with ${ow.managingAgent} serving as managing agent`;
    owText += ".";
    if (ow.portfolioSize && ow.portfolioSize > 1) {
      owText += ` The owner operates a portfolio of ${ow.portfolioSize} properties in the area.`;
    }
    bodyText(owText, narrativeWidth);
    y += 6;
  }

  if (payload.financials) {
    const fin = payload.financials;
    let finText = `Based on market rent analysis and RGB expense benchmarks (${fin.expenseCategory}), `;
    finText += `the property generates an estimated NOI of ${fmt(fin.estimatedNOI)} `;
    finText += `with an expense ratio of ${fmtPct(fin.expenseRatio * 100)}.`;
    bodyText(finText, narrativeWidth);
    y += 6;
  }

  if (payload.valuation) {
    const val = payload.valuation;
    let valText = `Our reconciled opinion of value ranges from ${fmtK(val.reconciledLow)} to ${fmtK(val.reconciledHigh)}, `;
    valText += `with a most likely value of ${fmtK(val.reconciledLikely)}`;
    if (val.salesCompBasis && val.incomeBasis) {
      valText += `, derived from both comparable sales and income capitalization approaches`;
    }
    valText += ".";
    bodyText(valText, narrativeWidth);
  }

  // Make sure y is past the box
  y = Math.max(y, boxY + actualBoxH + 20);

  if (payload.violations) {
    const v = payload.violations;
    const signalText = v.conditionSignal === "green" ? "The building is in good regulatory standing."
      : v.conditionSignal === "yellow" ? "The building has some compliance items requiring attention."
      : "The building has significant compliance concerns that should be addressed.";
    bodyText(signalText);
  }

  addFooter();

  // ─────────────────────────────────────────────────────────
  // PAGE 3 — Property Overview
  // ─────────────────────────────────────────────────────────

  doc.addPage();
  page++;
  y = 50;

  sectionTitle("Property Overview");

  // Location section
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...DARK);
  doc.text("Location", ML, y);
  y += 16;

  labelValue("Address", prop.address);
  labelValue("BBL", prop.bbl);
  labelValue("Borough", prop.borough);
  if (prop.neighborhood) labelValue("Neighborhood", prop.neighborhood);
  labelValue("Zip Code", prop.zip);
  y += 6;

  // Building section
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...DARK);
  doc.text("Building", ML, y);
  y += 16;

  labelValue("Building Class", `${prop.buildingClass}${prop.buildingClassDescription ? ` — ${prop.buildingClassDescription}` : ""}`);
  labelValue("Stories", `${prop.stories}`);
  labelValue("Total Units", `${prop.unitsTotal}`);
  if (prop.unitsResidential) labelValue("Residential Units", `${prop.unitsResidential}`);
  if (prop.unitsCommercial) labelValue("Commercial Units", `${prop.unitsCommercial}`);
  labelValue("Gross SF", fmtNum(prop.grossSqft));
  labelValue("Year Built", `${prop.yearBuilt}`);
  y += 6;

  // Lot section
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...DARK);
  doc.text("Lot & Zoning", ML, y);
  y += 16;

  labelValue("Lot Area", `${fmtNum(prop.lotSqft)} SF`);
  labelValue("Built FAR", prop.builtFAR.toFixed(2));
  labelValue("Max FAR", prop.maxFAR.toFixed(2));
  labelValue("Zoning", prop.zoning);
  if (prop.landmarkStatus) labelValue("Landmark", prop.landmarkStatus);
  y += 6;

  // Tax section
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...DARK);
  doc.text("Tax & Assessment", ML, y);
  y += 16;

  labelValue("Assessed Land", fmt(prop.assessedLandValue));
  labelValue("Assessed Total", fmt(prop.assessedTotalValue));
  labelValue("Market Value (DOF)", fmt(prop.marketValue));
  if (prop.taxClass) labelValue("Tax Class", prop.taxClass);
  y += 6;

  // Ownership
  if (payload.ownership) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text("Ownership", ML, y);
    y += 16;

    const ow = payload.ownership;
    labelValue("Registered Owner", ow.registeredOwner);
    if (ow.managingAgent) labelValue("Managing Agent", ow.managingAgent);
    if (ow.aiOwnerAnalysis) labelValue("Likely Owner (AI)", ow.aiOwnerAnalysis);
    if (ow.ownerConfidence) labelValue("Confidence", fmtPct(ow.ownerConfidence));
    if (ow.entityType) labelValue("Entity Type", ow.entityType);
    if (ow.portfolioSize && ow.portfolioSize > 1) labelValue("Portfolio Size", `${ow.portfolioSize} properties`);
    y += 6;
  }

  // Rent Stabilization
  if (payload.rentStabilization) {
    const rs = payload.rentStabilization;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text("Rent Stabilization", ML, y);
    y += 16;

    labelValue("Stabilized Units", `${rs.stabilizedUnits} of ${rs.totalUnits}`);
    labelValue("Stabilized %", fmtPct(rs.stabilizedPct));
    if (rs.rgbBlendedRate) labelValue("RGB Blended Rate", fmtPct(rs.rgbBlendedRate));
    for (const note of rs.notes) {
      mutedText(note);
    }
    y += 6;
  }

  // Last Sale
  if (prop.lastSalePrice) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text("Last Sale", ML, y);
    y += 16;

    labelValue("Sale Price", fmt(prop.lastSalePrice));
    if (prop.lastSaleDate) labelValue("Sale Date", fmtDate(prop.lastSaleDate));
    if (prop.lastSalePrice && prop.unitsTotal > 0) {
      labelValue("Price/Unit", fmt(prop.lastSalePrice / prop.unitsTotal));
    }
    if (prop.lastSalePrice && prop.grossSqft > 0) {
      labelValue("Price/SF", fmt(Math.round(prop.lastSalePrice / prop.grossSqft)));
    }
  }

  addFooter();

  // ─────────────────────────────────────────────────────────
  // PAGES 4-5 — Comparable Sales Analysis
  // ─────────────────────────────────────────────────────────

  if (payload.comps && payload.comps.length > 0 && payload.compSummary) {
    doc.addPage();
    page++;
    y = 50;

    sectionTitle("Comparable Sales Analysis");

    const cs = payload.compSummary;

    // Summary narrative
    let compNarr = `Based on ${cs.count} comparable sales`;
    if (cs.methodology) compNarr += `, ${cs.methodology.charAt(0).toLowerCase() + cs.methodology.slice(1)}`;
    compNarr += ".";
    bodyText(compNarr);
    y += 8;

    // Summary stats cards
    const cardW = (CW - 20) / 3;
    const cardH = 48;
    const cards: [string, string, RGB][] = [
      ["Median $/Unit", fmt(cs.medianPricePerUnit), PRIMARY],
      ["Price Range", `${fmtK(cs.priceRangeLow)} - ${fmtK(cs.priceRangeHigh)}`, ACCENT],
      ["Confidence", `${cs.confidence.toUpperCase()} (${cs.confidenceScore}/100)`, cs.confidence === "high" ? GREEN : cs.confidence === "medium" ? AMBER : RED],
    ];

    checkBreak(cardH + 16);
    let cx = ML;
    for (const [label, val, color] of cards) {
      doc.setFillColor(...BG_LIGHT);
      doc.roundedRect(cx, y, cardW, cardH, 4, 4, "F");
      doc.setDrawColor(...LIGHT_GRAY);
      doc.roundedRect(cx, y, cardW, cardH, 4, 4, "S");

      doc.setFontSize(7.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...GRAY);
      doc.text(label.toUpperCase(), cx + 10, y + 16);

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...color);
      doc.text(val, cx + 10, y + 36);

      cx += cardW + 10;
    }
    y += cardH + 20;

    // Comps table
    renderCompsTable(doc, payload.comps, y, ML, CW, W, MR);
    y = getCompsTableEndY(payload.comps.length, y);

    // Adjusted value from comps
    if (payload.compSummary.medianPricePerUnit > 0 && payload.property.unitsTotal > 0) {
      y += 12;
      checkBreak(50);
      const compValue = cs.medianPricePerUnit * payload.property.unitsTotal;
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...PRIMARY);
      doc.text("Sales Comparison Value Indication", ML, y);
      y += 16;
      labelValue("Median $/Unit", fmt(cs.medianPricePerUnit));
      labelValue("Subject Units", `${payload.property.unitsTotal}`);
      labelValue("Indicated Value", fmt(compValue));
    }

    addFooter();
  }

  // ─────────────────────────────────────────────────────────
  // PAGE — Financial Analysis
  // ─────────────────────────────────────────────────────────

  if (payload.financials) {
    doc.addPage();
    page++;
    y = 50;

    sectionTitle("Financial Analysis");

    const fin = payload.financials;

    // Income section
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text("Estimated Income", ML, y);
    y += 16;

    labelValue("Gross Rental Income", fmt(fin.estimatedGrossIncome));
    labelValue("Less: Vacancy", `(${fmtPct(fin.vacancyRate * 100)})  ${fmt(fin.estimatedGrossIncome * fin.vacancyRate)}`);
    doc.setDrawColor(...LIGHT_GRAY);
    doc.setLineWidth(0.5);
    doc.line(ML, y - 2, ML + 300, y - 2);
    labelValue("Effective Gross Income", fmt(fin.effectiveGrossIncome));
    y += 8;

    // Expense table
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text(`Operating Expenses (${fin.expenseCategory})`, ML, y);
    y += 16;

    renderExpenseTable(doc, fin.expenseLineItems, y, ML, CW, W, MR);
    y = getExpenseTableEndY(fin.expenseLineItems.length, y);

    // Total expenses
    checkBreak(40);
    doc.setFillColor(...PRIMARY_LIGHT);
    doc.rect(ML, y, CW, 18, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text("Total Operating Expenses", ML + 10, y + 13);
    doc.text(`${fmt(fin.expensePerUnit)}/unit`, ML + 280, y + 13, { align: "right" });
    doc.text(fmt(fin.totalExpenses), W - MR - 10, y + 13, { align: "right" });
    y += 26;

    // Adjustment notes
    if (fin.expenseAdjustmentNotes.length > 0) {
      mutedText("Adjustments: " + fin.expenseAdjustmentNotes.join(", "));
      y += 4;
    }

    // NOI
    checkBreak(30);
    doc.setFillColor(...PRIMARY);
    doc.rect(ML, y, CW, 22, "F");
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...WHITE);
    doc.text("Net Operating Income (NOI)", ML + 10, y + 16);
    doc.text(fmt(fin.estimatedNOI), W - MR - 10, y + 16, { align: "right" });
    y += 34;

    // Key ratios
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text("Key Ratios", ML, y);
    y += 16;

    labelValue("Expense Ratio", fmtPct(fin.expenseRatio * 100));
    if (fin.pricePerUnit) labelValue("Price Per Unit", fmt(fin.pricePerUnit));
    if (fin.pricePerSqft) labelValue("Price Per SF", fmtFull(fin.pricePerSqft));
    if (fin.grm) labelValue("Gross Rent Multiplier", fin.grm.toFixed(2) + "x");
    y += 8;

    // Cap rate analysis
    if (payload.capRate) {
      const cr = payload.capRate;
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...DARK);
      doc.text("Cap Rate Analysis", ML, y);
      y += 16;

      labelValue("Market Cap Rate", fmtPct(cr.marketCapRate));
      labelValue("Range", `${fmtPct(cr.rangeLow)} - ${fmtPct(cr.rangeHigh)}`);
      labelValue("Median", fmtPct(cr.median));
      labelValue("Suggested Exit Cap", fmtPct(cr.suggestedExitCap));
      labelValue("Trend", `${cr.trend} (${cr.trendBpsPerYear > 0 ? "+" : ""}${cr.trendBpsPerYear.toFixed(0)} bps/yr)`);
      labelValue("Confidence", cr.confidence.toUpperCase());
      labelValue("Comps Used", `${cr.compCount}`);
    }

    addFooter();
  }

  // ─────────────────────────────────────────────────────────
  // PAGE — Building Condition & Compliance
  // ─────────────────────────────────────────────────────────

  if (payload.violations || payload.permits || payload.energy || payload.litigation) {
    doc.addPage();
    page++;
    y = 50;

    sectionTitle("Building Condition & Compliance");

    // Violations
    if (payload.violations) {
      const v = payload.violations;

      // Condition signal badge
      const signalColor: RGB = v.conditionSignal === "green" ? GREEN : v.conditionSignal === "yellow" ? AMBER : RED;
      const signalLabel = v.conditionSignal === "green" ? "GOOD" : v.conditionSignal === "yellow" ? "FAIR" : "CONCERN";

      doc.setFillColor(...signalColor);
      doc.roundedRect(ML, y, 90, 24, 4, 4, "F");
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...WHITE);
      doc.text(signalLabel, ML + 45, y + 16, { align: "center" });
      y += 34;

      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...DARK);
      doc.text("HPD Violations", ML, y);
      y += 16;

      labelValue("Class A (Non-Hazardous)", `${v.hpdClassA}`);
      labelValue("Class B (Hazardous)", `${v.hpdClassB}`);
      labelValue("Class C (Immediately Hazardous)", `${v.hpdClassC}`);
      labelValue("Open Violations", `${v.hpdOpen}`);
      labelValue("Total Violations", `${v.hpdTotal}`);
      y += 6;

      if (v.dobViolations > 0) labelValue("DOB Violations", `${v.dobViolations}`);
      if (v.ecbViolations > 0) {
        labelValue("ECB Violations", `${v.ecbViolations}`);
        labelValue("ECB Penalties Outstanding", fmt(v.ecbPenalties));
      }
      y += 8;
    }

    // Permits
    if (payload.permits && payload.permits.recentPermits.length > 0) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...DARK);
      doc.text(`Recent Permits (${payload.permits.totalPermits} total)`, ML, y);
      y += 16;

      for (const pm of payload.permits.recentPermits) {
        checkBreak(30);
        doc.setFontSize(8.5);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...DARK);
        doc.text(`${pm.type}  —  ${pm.status}`, ML + 10, y);
        y += 12;
        if (pm.description) {
          doc.setFont("helvetica", "normal");
          doc.setTextColor(...GRAY);
          const descLines = doc.splitTextToSize(truncate(pm.description, 120), CW - 20);
          for (const dl of descLines) {
            doc.text(dl, ML + 10, y);
            y += 11;
          }
        }
        if (pm.filingDate) {
          doc.setFontSize(7.5);
          doc.setTextColor(...GRAY);
          doc.text(`Filed: ${fmtDate(pm.filingDate)}`, ML + 10, y);
          y += 12;
        }
        y += 4;
      }
      y += 6;
    }

    // Litigation
    if (payload.litigation && payload.litigation.totalCases > 0) {
      checkBreak(60);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...DARK);
      doc.text("Housing Court Litigation", ML, y);
      y += 16;

      labelValue("Active Cases", `${payload.litigation.activeCases}`);
      labelValue("Total Cases", `${payload.litigation.totalCases}`);
      y += 6;
    }

    // Energy
    if (payload.energy) {
      const e = payload.energy;
      checkBreak(80);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...DARK);
      doc.text("Energy & Emissions (LL84)", ML, y);
      y += 16;

      if (e.energyStarScore) labelValue("Energy Star Score", `${e.energyStarScore}`);
      if (e.grade) labelValue("Energy Grade", e.grade);
      if (e.siteEUI) labelValue("Site EUI", `${e.siteEUI.toFixed(1)} kBtu/sqft`);
      if (e.ghgTons) labelValue("GHG Emissions", `${e.ghgTons.toFixed(1)} metric tons CO2e`);
      if (e.ll97Status) labelValue("LL97 Status", e.ll97Status);
      if (e.ll97PenaltyEstimate) labelValue("LL97 Penalty Est.", fmt(e.ll97PenaltyEstimate));
    }

    addFooter();
  }

  // ─────────────────────────────────────────────────────────
  // PAGE — Market & Neighborhood Context
  // ─────────────────────────────────────────────────────────

  if (payload.neighborhood) {
    doc.addPage();
    page++;
    y = 50;

    sectionTitle("Market & Neighborhood Context");

    const n = payload.neighborhood;

    if (n.name) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...DARK);
      doc.text(n.name, ML, y);
      y += 18;
    }

    if (n.population) labelValue("Population", fmtNum(n.population));
    if (n.medianHouseholdIncome) labelValue("Median Household Income", fmt(n.medianHouseholdIncome));
    if (n.medianAge) labelValue("Median Age", `${n.medianAge}`);
    if (n.ownerOccupiedPct != null) labelValue("Owner Occupied", fmtPct(n.ownerOccupiedPct));
    if (n.renterOccupiedPct != null) labelValue("Renter Occupied", fmtPct(n.renterOccupiedPct));
    if (n.medianHomeValue) labelValue("Median Home Value", fmt(n.medianHomeValue));
    if (n.medianRent) labelValue("Median Rent", fmt(n.medianRent) + "/mo");
    y += 8;

    if (n.summary) {
      bodyText(n.summary);
    }

    addFooter();
  }

  // ─────────────────────────────────────────────────────────
  // PAGE — Valuation Opinion
  // ─────────────────────────────────────────────────────────

  if (payload.valuation) {
    doc.addPage();
    page++;
    y = 50;

    sectionTitle("Valuation Opinion");

    const val = payload.valuation;

    // Three-approach summary
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text("Valuation Approaches", ML, y);
    y += 18;

    // 1. Sales Comparison
    if (val.salesCompValue) {
      checkBreak(50);
      doc.setFillColor(...BG_LIGHT);
      doc.roundedRect(ML, y, CW, 40, 4, 4, "F");
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...PRIMARY);
      doc.text("1. SALES COMPARISON APPROACH", ML + 10, y + 14);
      doc.setFontSize(14);
      doc.setTextColor(...DARK);
      doc.text(fmt(val.salesCompValue), ML + 10, y + 32);
      if (val.salesCompBasis) {
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...GRAY);
        doc.text(truncate(val.salesCompBasis, 70), ML + 200, y + 32);
      }
      y += 50;
    }

    // 2. Income Approach
    if (val.incomeValue) {
      checkBreak(50);
      doc.setFillColor(...BG_LIGHT);
      doc.roundedRect(ML, y, CW, 40, 4, 4, "F");
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...PRIMARY);
      doc.text("2. INCOME APPROACH", ML + 10, y + 14);
      doc.setFontSize(14);
      doc.setTextColor(...DARK);
      doc.text(fmt(val.incomeValue), ML + 10, y + 32);
      if (val.incomeBasis) {
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...GRAY);
        doc.text(truncate(val.incomeBasis, 70), ML + 200, y + 32);
      }
      y += 50;
    }

    // 3. Reconciled Opinion
    checkBreak(80);
    doc.setFillColor(...PRIMARY);
    doc.roundedRect(ML, y, CW, 60, 4, 4, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...WHITE);
    doc.text("RECONCILED OPINION OF VALUE", ML + 10, y + 14);

    const thirdW = CW / 3;
    // Low
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("Low", ML + 10, y + 30);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(fmtK(val.reconciledLow), ML + 10, y + 48);

    // Likely
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("Most Likely", ML + thirdW + 10, y + 30);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(fmtK(val.reconciledLikely), ML + thirdW + 10, y + 48);

    // High
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("High", ML + thirdW * 2 + 10, y + 30);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(fmtK(val.reconciledHigh), ML + thirdW * 2 + 10, y + 48);

    y += 72;

    // Suggested listing
    if (val.suggestedListingLow && val.suggestedListingHigh) {
      checkBreak(30);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...DARK);
      doc.text("Suggested Listing Price Range", ML, y);
      y += 16;
      labelValue("Range", `${fmtK(val.suggestedListingLow)} — ${fmtK(val.suggestedListingHigh)}`);
      y += 10;
    }

    // Disclaimer
    y += 10;
    checkBreak(80);
    doc.setFillColor(255, 251, 235);
    doc.roundedRect(ML, y, CW, 80, 4, 4, "F");
    doc.setDrawColor(217, 119, 6);
    doc.setLineWidth(0.5);
    doc.roundedRect(ML, y, CW, 80, 4, 4, "S");

    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...AMBER);
    doc.text("IMPORTANT DISCLAIMER", ML + 10, y + 14);

    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 90, 40);
    const disclaimerLines = doc.splitTextToSize(val.disclaimer, CW - 20);
    let dly = y + 26;
    for (const dl of disclaimerLines) {
      doc.text(dl, ML + 10, dly);
      dly += 10;
    }

    addFooter();
  }

  // ─────────────────────────────────────────────────────────
  // LAST PAGE — Broker Bio & Disclaimer
  // ─────────────────────────────────────────────────────────

  doc.addPage();
  page++;
  y = 50;

  // Header bar
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, W, 60, "F");
  doc.setTextColor(...WHITE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("About Your Broker", ML, 38);

  y = 90;

  // Broker initials circle
  const initials = payload.generatedBy.name.split(" ").map(w => w[0]).join("").toUpperCase().slice(0, 2);
  doc.setFillColor(...ACCENT);
  doc.circle(ML + 30, y + 20, 25, "F");
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...WHITE);
  doc.text(initials, ML + 30, y + 26, { align: "center" });

  // Name & details
  const bioX = ML + 70;
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...DARK);
  doc.text(payload.generatedBy.name, bioX, y + 10);

  if (payload.generatedBy.title) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GRAY);
    doc.text(payload.generatedBy.title, bioX, y + 26);
  }

  y += 50;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...DARK);

  const contactLines: string[] = [];
  if (payload.generatedBy.email) contactLines.push(payload.generatedBy.email);
  if (payload.generatedBy.phone) contactLines.push(payload.generatedBy.phone);
  if (payload.generatedBy.licenseNumber) contactLines.push(`NYS RE License #${payload.generatedBy.licenseNumber}`);

  for (const cl of contactLines) {
    doc.text(cl, bioX, y);
    y += 14;
  }

  y += 10;

  // Company info
  doc.setDrawColor(...LIGHT_GRAY);
  doc.setLineWidth(0.5);
  doc.line(ML, y, W - MR, y);
  y += 16;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PRIMARY);
  doc.text(payload.branding.companyName, ML, y);
  y += 16;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...DARK);
  if (payload.branding.address) { doc.text(payload.branding.address, ML, y); y += 14; }
  if (payload.branding.phone) { doc.text(payload.branding.phone, ML, y); y += 14; }
  if (payload.branding.email) { doc.text(payload.branding.email, ML, y); y += 14; }
  if (payload.branding.website) { doc.text(payload.branding.website, ML, y); y += 14; }

  y += 30;

  // Legal disclaimer
  doc.setDrawColor(...LIGHT_GRAY);
  doc.line(ML, y, W - MR, y);
  y += 16;

  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(...GRAY);

  const legalDisclaimer =
    "This Broker Opinion of Value (BOV) has been prepared by the above-named broker as an informal estimate of market value. " +
    "It is not a formal appraisal and should not be used as such. The information contained herein is based on publicly available " +
    "data sources including NYC Open Data, HPD, DOB, ACRIS, and Census records. While efforts have been made to ensure accuracy, " +
    "the broker makes no warranty or guarantee regarding the completeness or accuracy of the data. This BOV is intended solely " +
    "for discussion purposes between the broker and the property owner. Any reliance on this document for lending, legal, tax, " +
    "or investment decisions is at the reader's own risk. A formal appraisal by a New York State licensed appraiser is recommended " +
    "for any transaction requiring a definitive opinion of value.";

  const legalLines = doc.splitTextToSize(legalDisclaimer, CW);
  for (const ll of legalLines) {
    checkBreak(10);
    doc.text(ll, ML, y);
    y += 10;
  }

  // Footer
  y += 20;
  doc.setFontSize(7);
  doc.setTextColor(...GRAY);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by VettdRE \u2014 AI-Powered Real Estate Intelligence", W / 2, H - 20, { align: "center" });

  return doc;

  // ── Table Renderers ─────────────────────────────────────────

  function renderCompsTable(d: jsPDF, comps: BovCompData[], startY: number, ml: number, cw: number, w: number, mr: number): void {
    const colWidths = [130, 65, 80, 70, 60, 50, 57];
    const rowH = 16;
    const headers = ["Address", "Sale Date", "Sale Price", "$/Unit", "Units", "Cap Rate", "Score"];

    // Header row
    checkBreak(rowH + 4);
    d.setFillColor(...PRIMARY);
    d.rect(ml, y, cw, rowH, "F");
    d.setFontSize(7.5);
    d.setFont("helvetica", "bold");
    d.setTextColor(...WHITE);
    let hx = ml;
    for (let i = 0; i < headers.length; i++) {
      d.text(headers[i], hx + 5, y + 11);
      hx += colWidths[i];
    }
    y += rowH;

    // Data rows
    for (let ri = 0; ri < comps.length; ri++) {
      checkBreak(rowH);
      const comp = comps[ri];
      if (ri % 2 === 0) {
        d.setFillColor(...BG_LIGHT);
        d.rect(ml, y, cw, rowH, "F");
      }

      d.setFontSize(7.5);
      d.setFont("helvetica", "normal");
      d.setTextColor(...DARK);

      let rx = ml;
      const cells = [
        truncate(comp.address, 22),
        fmtDate(comp.saleDate),
        fmtK(comp.salePrice),
        fmt(comp.pricePerUnit),
        `${comp.units}`,
        comp.estimatedCapRate ? fmtPct(comp.estimatedCapRate) : "\u2014",
        `${comp.similarityScore}%`,
      ];

      for (let ci = 0; ci < cells.length; ci++) {
        d.text(cells[ci], rx + 5, y + 11);
        rx += colWidths[ci];
      }
      y += rowH;
    }
  }

  function getCompsTableEndY(count: number, startY: number): number {
    return y; // y is already updated by renderCompsTable
  }

  function renderExpenseTable(d: jsPDF, items: BovExpenseLineItem[], startY: number, ml: number, cw: number, w: number, mr: number): void {
    const rowH = 15;

    // Header
    checkBreak(rowH + 4);
    d.setFillColor(...PRIMARY);
    d.rect(ml, y, cw, rowH, "F");
    d.setFontSize(8);
    d.setFont("helvetica", "bold");
    d.setTextColor(...WHITE);
    d.text("Expense Item", ml + 10, y + 11);
    d.text("$/Unit/Year", ml + 280, y + 11, { align: "right" });
    d.text("Total Annual", w - mr - 10, y + 11, { align: "right" });
    y += rowH;

    for (let i = 0; i < items.length; i++) {
      checkBreak(rowH);
      const item = items[i];
      if (i % 2 === 0) {
        d.setFillColor(...BG_LIGHT);
        d.rect(ml, y, cw, rowH, "F");
      }

      d.setFontSize(8);
      d.setFont("helvetica", "normal");
      d.setTextColor(...DARK);
      d.text(item.label, ml + 10, y + 11);
      d.text(fmt(item.perUnit), ml + 280, y + 11, { align: "right" });
      d.text(fmt(item.totalAnnual), w - mr - 10, y + 11, { align: "right" });
      y += rowH;
    }
  }

  function getExpenseTableEndY(count: number, startY: number): number {
    return y;
  }
}

// ── Blob Export ─────────────────────────────────────────────

export function generateBovPdfBlob(payload: BovPayload): Blob {
  const doc = generateBovPdf(payload);
  return doc.output("blob");
}

// ── Filename Helper ─────────────────────────────────────────

export function getBovFilename(payload: BovPayload): string {
  const addr = sanitizeFilename(payload.property.address);
  const date = payload.generatedAt.slice(0, 10);
  return `BOV-${addr}-${date}.pdf`;
}
