// ============================================================
// Shared PDF Helpers — reusable drawing utilities for jsPDF
// Used by investment-summary-pdf.ts (and future PDF generators).
// Patterns extracted from bov-pdf.ts conventions.
// ============================================================

import jsPDF from "jspdf";

// ── Types ────────────────────────────────────────────────────

export type RGB = [number, number, number];

export interface PdfContext {
  doc: jsPDF;
  y: number;
  page: number;
  W: number;
  H: number;
  ML: number;
  MR: number;
  CW: number;
  PRIMARY: RGB;
  ACCENT: RGB;
  companyName: string;
}

// ── Standard Colors ──────────────────────────────────────────

export const PDF_COLORS = {
  WHITE: [255, 255, 255] as RGB,
  BLACK: [33, 33, 33] as RGB,
  DARK: [15, 23, 42] as RGB,
  GRAY: [100, 116, 139] as RGB,
  LIGHT_GRAY: [226, 232, 240] as RGB,
  BG_LIGHT: [248, 250, 252] as RGB,
  GREEN: [22, 163, 74] as RGB,
  RED: [220, 38, 38] as RGB,
  AMBER: [217, 119, 6] as RGB,
};

// ── Color Utility ────────────────────────────────────────────

export function hexToRgb(hex: string): RGB {
  const h = hex.replace("#", "");
  return [
    parseInt(h.slice(0, 2), 16) || 30,
    parseInt(h.slice(2, 4), 16) || 64,
    parseInt(h.slice(4, 6), 16) || 175,
  ];
}

export function tintColor(color: RGB, amount: number): RGB {
  return [
    Math.min(255, color[0] + Math.round((255 - color[0]) * amount)),
    Math.min(255, color[1] + Math.round((255 - color[1]) * amount)),
    Math.min(255, color[2] + Math.round((255 - color[2]) * amount)),
  ];
}

// ── Formatters ───────────────────────────────────────────────

export function formatCurrency(n: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(n);
}

export function formatCurrencyFull(n: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
  }).format(n);
}

export function formatCompact(n: number): string {
  if (n >= 1e6) return `$${(n / 1e6).toFixed(2)}M`;
  if (n >= 1000) return `$${Math.round(n / 1000).toLocaleString()}K`;
  return formatCurrency(n);
}

export function formatNumber(n: number): string {
  return new Intl.NumberFormat("en-US").format(n);
}

export function formatPercent(n: number): string {
  return `${n.toFixed(1)}%`;
}

export function formatDate(iso: string): string {
  try {
    return new Intl.DateTimeFormat("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    }).format(new Date(iso));
  } catch {
    return iso || "N/A";
  }
}

// ── Context Factory ──────────────────────────────────────────

export function createPdfContext(
  doc: jsPDF,
  branding: { primaryColor: string; accentColor: string; companyName: string },
): PdfContext {
  return {
    doc,
    y: 0,
    page: 1,
    W: 612,
    H: 792,
    ML: 50,
    MR: 50,
    CW: 512,
    PRIMARY: hexToRgb(branding.primaryColor),
    ACCENT: hexToRgb(branding.accentColor),
    companyName: branding.companyName,
  };
}

// ── Page Break ───────────────────────────────────────────────

export function checkPageBreak(ctx: PdfContext, needed: number): void {
  if (ctx.y + needed > ctx.H - 60) {
    drawFooter(ctx);
    ctx.doc.addPage();
    ctx.page++;
    ctx.y = 50;
  }
}

// ── Footer ───────────────────────────────────────────────────

export function drawFooter(ctx: PdfContext): void {
  const { doc, W, H, ML, MR } = ctx;
  doc.setFontSize(7);
  doc.setTextColor(...PDF_COLORS.GRAY);
  doc.setFont("helvetica", "normal");
  doc.text(ctx.companyName, ML, H - 20);
  doc.text(`Page ${ctx.page}`, W / 2, H - 20, { align: "center" });
  doc.text("Generated by VettdRE", W - MR, H - 20, { align: "right" });
}

// ── Section Header ───────────────────────────────────────────

export function drawSectionHeader(ctx: PdfContext, text: string): void {
  checkPageBreak(ctx, 30);
  const { doc, ML, W, MR } = ctx;
  doc.setFontSize(13);
  doc.setTextColor(...ctx.PRIMARY);
  doc.setFont("helvetica", "bold");
  doc.text(text, ML, ctx.y);
  doc.setDrawColor(...PDF_COLORS.LIGHT_GRAY);
  doc.setLineWidth(0.5);
  doc.line(ML, ctx.y + 4, W - MR, ctx.y + 4);
  ctx.y += 22;
}

// ── Label-Value Pair ─────────────────────────────────────────

export function drawLabelValue(
  ctx: PdfContext,
  label: string,
  value: string,
  indent = 0,
): void {
  checkPageBreak(ctx, 14);
  const { doc, ML } = ctx;
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...PDF_COLORS.GRAY);
  doc.text(label, ML + indent, ctx.y);
  doc.setTextColor(...PDF_COLORS.DARK);
  doc.setFont("helvetica", "bold");
  doc.text(value, ML + 180 + indent, ctx.y);
  ctx.y += 14;
}

// ── Body Text (wrapped) ─────────────────────────────────────

export function drawBodyText(
  ctx: PdfContext,
  text: string,
  maxWidth?: number,
): void {
  const { doc, ML, CW } = ctx;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...PDF_COLORS.DARK);
  const lines = doc.splitTextToSize(text, maxWidth || CW);
  for (const line of lines) {
    checkPageBreak(ctx, 13);
    doc.text(line, ML, ctx.y);
    ctx.y += 13;
  }
}

// ── Muted Text ───────────────────────────────────────────────

export function drawMutedText(ctx: PdfContext, text: string): void {
  const { doc, ML, CW } = ctx;
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(...PDF_COLORS.GRAY);
  const lines = doc.splitTextToSize(text, CW);
  for (const line of lines) {
    checkPageBreak(ctx, 12);
    doc.text(line, ML, ctx.y);
    ctx.y += 12;
  }
}

// ── Table ────────────────────────────────────────────────────

export interface TableColumn {
  label: string;
  width: number;
  align?: "left" | "center" | "right";
}

export function drawTable(
  ctx: PdfContext,
  columns: TableColumn[],
  rows: string[][],
): void {
  const { doc, ML } = ctx;
  const ROW_H = 16;
  const HEADER_H = 18;

  // Header row
  checkPageBreak(ctx, HEADER_H + ROW_H * Math.min(rows.length, 3));
  doc.setFillColor(...ctx.PRIMARY);
  doc.rect(ML, ctx.y - 11, ctx.CW, HEADER_H, "F");
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...PDF_COLORS.WHITE);

  let colX = ML;
  for (const col of columns) {
    const align = col.align || "left";
    const textX = align === "right" ? colX + col.width - 4 : align === "center" ? colX + col.width / 2 : colX + 4;
    doc.text(col.label, textX, ctx.y, { align });
    colX += col.width;
  }
  ctx.y += HEADER_H - 4;

  // Data rows
  for (let i = 0; i < rows.length; i++) {
    checkPageBreak(ctx, ROW_H);
    if (i % 2 === 0) {
      doc.setFillColor(...PDF_COLORS.BG_LIGHT);
      doc.rect(ML, ctx.y - 10, ctx.CW, ROW_H, "F");
    }

    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...PDF_COLORS.DARK);

    colX = ML;
    for (let c = 0; c < columns.length; c++) {
      const col = columns[c];
      const val = rows[i][c] || "";
      const align = col.align || "left";
      const textX = align === "right" ? colX + col.width - 4 : align === "center" ? colX + col.width / 2 : colX + 4;
      doc.text(val, textX, ctx.y, { align });
      colX += col.width;
    }
    ctx.y += ROW_H;
  }
  ctx.y += 4;
}

// ── Key-Value Grid (2-column or 3-column) ────────────────────

export function drawKeyValueGrid(
  ctx: PdfContext,
  pairs: { label: string; value: string }[],
  columnsPerRow = 2,
): void {
  const { doc, ML, CW } = ctx;
  const colWidth = CW / columnsPerRow;
  const ROW_H = 16;

  for (let i = 0; i < pairs.length; i += columnsPerRow) {
    checkPageBreak(ctx, ROW_H);

    // Alternating background
    if (Math.floor(i / columnsPerRow) % 2 === 0) {
      doc.setFillColor(...PDF_COLORS.BG_LIGHT);
      doc.rect(ML, ctx.y - 10, CW, ROW_H, "F");
    }

    for (let c = 0; c < columnsPerRow && i + c < pairs.length; c++) {
      const pair = pairs[i + c];
      const baseX = ML + c * colWidth;

      doc.setFontSize(7.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...PDF_COLORS.GRAY);
      doc.text(pair.label, baseX + 4, ctx.y);

      doc.setFont("helvetica", "bold");
      doc.setTextColor(...PDF_COLORS.DARK);
      doc.text(pair.value, baseX + colWidth / 2 + 20, ctx.y);
    }
    ctx.y += ROW_H;
  }
  ctx.y += 4;
}

// ── Cover Page ───────────────────────────────────────────────

export function drawCoverPage(
  ctx: PdfContext,
  opts: {
    title: string;
    subtitle?: string;
    address: string;
    locationLine?: string;
    website?: string | null;
  },
): void {
  const { doc, W, ML } = ctx;

  // Full-width primary header bar
  doc.setFillColor(...ctx.PRIMARY);
  doc.rect(0, 0, W, 100, "F");

  // Company name
  doc.setTextColor(...PDF_COLORS.WHITE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(ctx.companyName.toUpperCase(), ML, 55);

  if (opts.website) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(opts.website, ML, 72);
  }

  // Document title
  ctx.y = 180;
  doc.setTextColor(...PDF_COLORS.GRAY);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(opts.title.toUpperCase(), W / 2, ctx.y, { align: "center" });
  ctx.y += 30;

  // Address — centered large
  doc.setTextColor(...PDF_COLORS.DARK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  const addrLines = doc.splitTextToSize(opts.address, ctx.CW);
  for (const line of addrLines) {
    doc.text(line, W / 2, ctx.y, { align: "center" });
    ctx.y += 36;
  }

  // Subtitle (e.g., deal structure label)
  if (opts.subtitle) {
    ctx.y += 8;
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...ctx.PRIMARY);
    doc.text(opts.subtitle, W / 2, ctx.y, { align: "center" });
    ctx.y += 24;
  }

  // Location line
  if (opts.locationLine) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...PDF_COLORS.GRAY);
    doc.text(opts.locationLine, W / 2, ctx.y, { align: "center" });
    ctx.y += 20;
  }

  // Accent bar at bottom
  doc.setFillColor(...ctx.ACCENT);
  doc.rect(0, ctx.H - 40, W, 6, "F");
}

// ── Sanitize Filename ────────────────────────────────────────

export function sanitizeFilename(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .substring(0, 60);
}
