steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=https://dhphradjmajfjuvshyra.supabase.co'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRocGhyYWRqbWFqZmp1dnNoeXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExNTY3MjIsImV4cCI6MjA4NjczMjcyMn0.NA3iZnmbcZUwMc_EJp6w0Qc_gzNjYAjn68Z1QrWdawc'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/vettdre:$BUILD_ID'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/vettdre:$BUILD_ID'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vettdre'
      - '--image'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/vettdre:$BUILD_ID'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,DIRECT_URL=DIRECT_URL:latest,NEXT_PUBLIC_SUPABASE_URL=NEXT_PUBLIC_SUPABASE_URL:latest,NEXT_PUBLIC_SUPABASE_ANON_KEY=NEXT_PUBLIC_SUPABASE_ANON_KEY:latest,ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,PDL_API_KEY=PDL_API_KEY:latest,APOLLO_API_KEY=APOLLO_API_KEY:latest,GMAIL_CLIENT_ID=GMAIL_CLIENT_ID:latest,GMAIL_CLIENT_SECRET=GMAIL_CLIENT_SECRET:latest,GMAIL_REDIRECT_URI=GMAIL_REDIRECT_URI:latest'
images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/vettdre:$BUILD_ID'
